spring.application.name=fullstack-backend
spring.datasource.url=jdbc:mysql://153.92.15.40:3306/u626686198_my_manager
spring.datasource.username=u626686198_Y3S3
spring.datasource.password=Mymanager@2025
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
